import { Divider } from "@/app/(posts)/components/divider";
import { AuthorApiService } from "@/services/author-api-service";
import type { Metadata } from "next";
import { Contact } from "./components/contact";
import { Hero } from "./components/hero";
import { PostList } from "./components/post-list";

const appName = process.env.NEXT_PUBLIC_APP_NAME

export const metadata: Metadata = {
  title: `${appName} | Início`,
  description: "Generated by create next app",
};

const authorApiService = new AuthorApiService()

export default async function Home() {
  const { author } = await authorApiService.getAuthor()

  return (
    <>
      <Hero
        avatarUrl={author.avatarUrl}
        bio={author.bio}
        course={author.course}
        name={author.name}
      />
      <Divider />

      <PostList maxContentLengh={6} />

      <Contact
        email={author.social.email}
        github={author.social.github}
        linkedin={author.social.linkedin}
      />
    </>
  );
}
