import { Navbar } from "@/components/navbar/navbar";
import { AuthorApiService } from "@/services/author-api-service";
import type { Metadata } from "next";
import { Chakra_Petch, Inter } from "next/font/google";
import { cookies } from "next/headers";
import { NuqsAdapter } from "nuqs/adapters/next";
import "./globals.css";

const fontChackra = Chakra_Petch({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-chackra'
})

const fontInter = Inter({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-inter'
})

const appName = process.env.NEXT_PUBLIC_APP_NAME

export const metadata: Metadata = {
  title: appName,
  description: "Generated by create next app",
};

const authorApiService = new AuthorApiService()

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value || "light";

  const { author } = await authorApiService.getAuthor()

  return (
    <html lang="en" className={theme}>
      <body
        className={`${fontChackra.variable} ${fontInter.variable} antialiased w-full h-screen bg-white relative flex items-center flex-col font-inter`}
      >
        <NuqsAdapter>
          <main className="w-full px-8 md:px-32 py-10 max-w-[1600px] flex flex-col gap-16 items-center">
            <Navbar authorName={author.name} />
            {children}
          </main>

          <footer className="text-slate-400 mt-auto pb-8 px-8 w-full text-center">
            © Copyright 2025. Produzido por {author.name}
          </footer>
        </NuqsAdapter>
      </body>
    </html>
  );
}
