import type { Metadata } from "next";
import { Chakra_Petch, Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/navbar";
import { cookies } from "next/headers";
import Image from "next/image";
import gradient from "@/assets/gradient.png"

const fontChackra = Chakra_Petch({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-chackra'
})

const fontInter = Inter({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-inter'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value || "light";

  return (
    <html lang="en" className={theme}>
      <body
        className={`${fontChackra.variable} ${fontInter.variable} antialiased w-full h-screen bg-white relative flex items-center flex-col`}
      >
        <main className="w-full px-32 py-10 max-w-[1600px]">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
