import type { Metadata } from "next";
import { PostList } from "../components/post-list";

const appName = process.env.NEXT_PUBLIC_APP_NAME

export const metadata: Metadata = {
  title: `${appName} | Blog Posts`,
  description: "Generated by create next app",
};

export default async function Blog() {
  return (
    <div className="gradient-background">
      <PostList maxContentLengh={9} />
    </div>
  );
}
